BASE_TASK_CONFIG_PATH: habitat_extensions/config/vlnce_task_aug_intuit_pano.yaml
TRAINER_NAME: daggerlawintuition
ENV_NAME: "VLNCEDaggerEnv" #better for eval
#ENV_NAME: "VLNCEDaggerIntuitionEnv"
SIMULATOR_GPU_ID: 0
TORCH_GPU_ID: 0
NUM_PROCESSES: 8
NUM_UPDATES: 100
TOTAL_NUM_STEPS: -1.0
NUM_CHECKPOINTS: 10.0
CHECKPOINT_INTERVAL: -1.0
TENSORBOARD_DIR: experiments/tensorboard_dirs/intuit/hpc2/cma_pm_aug
CHECKPOINT_FOLDER: experiments/checkpoints/intuit/hpc2/cma_pm_aug
EVAL_CKPT_PATH_DIR: experiments/checkpoints/intuit/hpc2/cma_pm_aug
STATS_EVAL_DIR: experiments/evaluations/intuit/hpc2/cma_pm_aug

EVAL:
  USE_CKPT_CONFIG: False
  #SPLIT: val_unseen
  SPLIT: val_seen
  EPISODE_COUNT: 50000

DAGGER:
  LOAD_FROM_CKPT: False
  CKPT_TO_LOAD: experiments/checkpoints/intuit/phase1/cma_pm_aug/ckpt.19.pth
  ITERATIONS: 1
  EPOCHS: 45
  UPDATE_SIZE: 157232
  BATCH_SIZE: 5
  P: 1.0
  PRELOAD_LMDB_FEATURES: True
  LMDB_FEATURES_DIR: experiments/trajectories_dirs/intuit/hpc2/cma_pm_aug/trajectories.lmdb

MODEL:
  INSTRUCTION_ENCODER:
    bidirectional: True

  CMA:
    use: True

  PROGRESS_MONITOR:
    use: True
