BASE_TASK_CONFIG_PATH: habitat_extensions/config/vlnce_task_aug_intuit_pano.yaml
TRAINER_NAME: daggerlawintuition
ENV_NAME: "VLNCEDaggerEnv" #better for eval
#ENV_NAME: "VLNCEDaggerIntuitionEnv"
SIMULATOR_GPU_ID: 0
TORCH_GPU_ID: 0
NUM_PROCESSES: 4
NUM_UPDATES: 100
TOTAL_NUM_STEPS: -1.0
NUM_CHECKPOINTS: 10.0
CHECKPOINT_INTERVAL: -1.0
TENSORBOARD_DIR: experiments/tensorboard_dirs/intuit/phase1/cma_pm_aug
CHECKPOINT_FOLDER: experiments/checkpoints/intuit/dagg/cma_pm_aug
EVAL_CKPT_PATH_DIR: experiments/checkpoints/intuit/dagg/cma_pm_aug/ckpt.4.pth
STATS_EVAL_DIR: experiments/evaluations/intuit/phase1/cma_pm_aug

EVAL:
  USE_CKPT_CONFIG: False
  SPLIT: local_train
  EPISODE_COUNT: 200

DAGGER:
  LOAD_FROM_CKPT: True
  CKPT_TO_LOAD: experiments/checkpoints/intuit/phase1/cma_pm_aug/ckpt.19.pth
  ITERATIONS: 1
  EPOCHS: 5
  UPDATE_SIZE: 200
  BATCH_SIZE: 5
  P: 0.7
  PRELOAD_LMDB_FEATURES: False
  LMDB_FEATURES_DIR: experiments/trajectories_dirs/intuit/multiProc/cma_pm_aug/trajectories.lmdb

MODEL:
  INSTRUCTION_ENCODER:
    bidirectional: True

  CMA:
    use: True

  PROGRESS_MONITOR:
    use: True
